name: Continous Intergration
on: push
env:
  DB_Name: test
  DB_User: root
  DB_Password: StronPassword
jobs:
  run_code_check:
    runs-on: ubuntu-latest
    steps:
      - name: Mysql setup
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e "ALTER USER '${DB_User}'@'localhost' IDENTIFIED BY '${DB_Password}';"
          mysql -uroot -p${DB_Password} -e "create database ${DB_Name};"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run Linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run Tests
        run: go test -v ./...
